global using CommandLine;
global using ConsoleTables;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using WildcardsUtilities.Async;
global using WildcardsUtilities.Common;
global using WildcardsUtilities.Scanning;
