global using Microsoft.EntityFrameworkCore;
global using Strongly;
global using System.Management;
global using System.Security.Cryptography;
global using System.Text;
global using WildcardsUtilities.Common;
global using WildcardsUtilities.Scanning.DbItems;
global using WildcardsUtilities.Scanning.Identifiers;
global using Z.BulkOperations;